version: '3.8'

services:
  mysql-server:
    image: mysql:8.0-oracle
    hostname: mysql-server
    container_name: mysql-server
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init_sql:/docker-entrypoint-initdb.d
    networks:
      - zabbix-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  zabbix-server:
    image: zabbix/zabbix-server-mysql:7.0-ubuntu-latest
    hostname: zabbix-server 
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
    ports:
      - "10051:10051"
    depends_on:
      - mysql-server
    networks:
      - zabbix-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:7.0-ubuntu-latest
    hostname: zabbix-web
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
      PHP_TZ: Asia/Shanghai
    ports:
      - "8080:8080"
    depends_on:
      - zabbix-server
    networks:
      - zabbix-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  zabbix-agent:
    image: zabbix/zabbix-agent:7.0-ubuntu-latest
    hostname: zabbix-agent
    container_name: zabbix-agent
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: 10051
    ports:
      - "10050"
    depends_on:
      - zabbix-server
    networks:
      - zabbix-network
    volumes:
      - ./zabbix_agentd.conf:/etc/zabbix/zabbix_agentd.conf:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  zabbix-network:
    driver: bridge
